paths:
  /products:
    get:
      tags:
        - Products
      summary: Get all products.
      description: Get all products.
      operationId: getProducts
      parameters:
        - name: limit
          in: query
          description: Number of products to return.
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          required: false
        - name: page
          in: query
          description: Page number of products to return.
          schema:
            type: integer
            minimum: 1
            default: 1
          required: false
        - name: sort
          in: query
          description: Sort products by field.
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          required: false
        - name: query
          in: query
          description: Search products by title.
          schema:
            type: string
            example: 'mongo'
          required: false
        - name: status
          in: query
          description: Filter products by status.
          schema:
            type: string
            enum: [available, nonavaiable]
            default: available
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Internal server error.

    post:
      tags:
        - Products
      summary: Create a new product.
      description: Create a new product.
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Error Authorization.
        '400':
          description: Wrong Data Format.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Wrong Data Format.
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Internal server error.

  /products/{pid}:
    parameters:
      - name: pid
        in: path
        required: true
        description: Product's ID.
        example: 647281f59f14215ff253872e
    
    get:
      tags:
        - Products
      summary: Get product by ID.
      description: Get Product by ID.
      operationId: getProduct
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Internal server error.

    put:
      tags:
        - Products
      summary: Update a product.
      description: Update a product.
      operationId: updateProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Authorization Error.
        '400':
          description: Wrong Data Format.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Wrong Data Format.
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Internal server error.

    delete:
      tags:
        - Products
      summary: Delete a product.
      description: Delete a product.
      operationId: deleteProduct

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Authorization Error.
        '400':
          description: Wrong Data Format.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Wrong Data Format.
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
                example:
                  status: error
                  error: Internal server error.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          default: aaaa0000aaaa0000aaaa0000
          description: Product's ID.
        title:
          type: string
          default: Este es un título
          description: Product's Title.
        description:
          type: string
          default: Esto es una descripción
          description: Product's Description.
        price:
          type: number
          default: 100
          description: Product's Price.
        stock:
          type: number
          default: 100
          description: Product's Stock.
        thumbnails:
          type: string
          default: Sin imagen
          description: Product's Thumbnails.
        code:
          type: number
          default: aaa111
          description: Product's Code.
        category:
          type: string
          default: Sin categoría
          description: Product's Category.
        status:
          type: boolean
          default: true
          description: Product's Status.

    Error:
      type: object
      properties:
        status:
          example: 'error'
        error:
          example: 'Error de Autorizacion'

    NewProduct:
      type: object
      properties:
        title:
          type: string
          default: Este es un título
          description: Product's Title.
        description:
          type: string
          default: Esto es una descripción
          description: Product's Description.
        price:
          type: number
          default: 100
          description: Product's Price.
        stock:
          type: number
          default: 100
          description: Product's Stock.
        thumbnails:
          type: string
          default: Sin imagen
          description: Product's Thumbnails.
        code:
          type: number
          default: aaa111
          description: Product's Code.
        category:
          type: string
          default: Sin categoría
          description: Product's Category.

